### ISSUE TITLE
TimeStamp

### ISSUE THREAD

**Issue by radonyizsolt** [SkeLLLa/gulp-version-append#2]
Hey there!

Could you implement a timestamp option beside version?

Cheers

**Comment by SkeLLLa** [comment]
@radonyizsolt added in 0.1.0 version.

If something is wrong feel free to reopen this issue.

**Comment by SkeLLLa** [comment]
Oh, just read your comment again and understood that you may be asked for some different functionality like:

```
.../file.js?v=2.0.0.20151123
```

Am I right?

**Comment by radonyizsolt** [comment]
I thought that it would be nice if i can add more than 1 parameters. For example:

```
?v=@version@&t=@timestamp@
```

I changed my gulpfile in a way that i can define an "enviroment" key and if its "develop" then i change appendType key to "timestamp", else its "version" by default.

I changed your code a little bit for just local developing, if you want so see that i can attach it :)

**Comment by SkeLLLa** [comment]
Understood. As for production one parameter is enough to prevent browser to load some resource from cache. So more than one parameters will be not commonly used in prod. And this plugin is mainly developed for production, where caching is utilized very often. E.g. this plugin will be helpful if you distribute css, js and other static files via cloudfront or some other cdn. And when parameter changes it will force cdn to  actualize resource from origin.

And as for development env mainly cache is not used (at least such cache as cdn's cache, that's quite lazy on updating), so when I develop my apps I don't use this plugin. I enable it only for production builds. 

Anyway I'm glad if my code helped you.

**Comment by radonyizsolt** [comment]
Understood. I need it in delevop mode to push it to a test server where a Tester can check everything, so there is a lot of changes and i didn't want to increase every time the version. But anyway i made that happen with your code and a little plus. 

So thanks for everything! 
Cheers
