### ISSUE TITLE
gVersionAppend is not defined

### ISSUE THREAD

**Issue by starwavelin** [SkeLLLa/gulp-version-append#3]
Hi SkeLLLa, 

I encountered "ReferenceError: gVersionAppend is not defined" when following your example set in the /example folder. I also tried to use "versionAppend" as indicated on your README but the similar issue "ReferenceError: versionAppend is not defined" occurred. Could you help with this? Many thanks!

**Comment by SkeLLLa** [comment]
@starwavelin `gVersionAppend` as well as `versionAppend` is a variable that stands for module.

So you need to define it in your code.

```
var versionAppend = require('gulp-version-append');
```

or you can use https://www.npmjs.com/package/gulp-load-plugins and this module will be available via

```
$.versionAppend
```

**Comment by starwavelin** [comment]
Hi @SkeLLLa I got rid of those errors based on your hint. Many thanks for your help and update on README.md as well :)

**Comment by SkeLLLa** [comment]
@starwavelin I'm glad I can help.
