### ISSUE TITLE
srcset support

### ISSUE THREAD

**Issue by samuelcarreira** [SkeLLLa/gulp-version-append#5]
The original regex expression didn't work on some parts of my code (srcset tags)

Sample:
`<picture>
      <source type="image/webp" srcset="{{root}}img/sarah@2x.webp?v=@version@ 2x, {{root}}img/sarah.webp?v=@version@ 1x" />
      <img srcset="{{root}}img/sarah@2x.jpg?v=@version@ 2x" src="{{root}}img/sarah.jpg" alt="Sarah">
    </picture>`

Can you change the code to support srcsets (format without the end quotation mark)?

**Comment by SkeLLLa** [comment]
@samcpt, ok I can try to do this.

**Comment by SkeLLLa** [comment]
@samcpt, I've updated module, please try new one, it should handle srcsets properly.

**Comment by samuelcarreira** [comment]
@SkeLLLa thank you very much, it works fine!
