### ISSUE TITLE
How can i get this working for favicon ?

### ISSUE THREAD

**Issue by samja666** [SkeLLLa/gulp-version-append#8]
I want the below line in my index.html 
`<link rel="shortcut icon" href="abc/def/favicon.ico?v=@version@" />`

to get converted into
`<link rel="shortcut icon" href="abc/def/favicon.ico?v=1.2.0" />`

**Comment by SkeLLLa** [comment]
@samja666 have you tried soething like (see: versionAppend param's array)
```js
gulp.task('html', function(){
    return gulp.src(path.join(__dirname, '*.html'))
          .pipe(versionAppend(['html', 'js', 'css', 'ico']))
```
