### ISSUE TITLE
Different version for different css using gulp angular

### ISSUE THREAD

**Issue by pinal-r** [SkeLLLa/gulp-version-append#9]
I have two css

```
<link rel="stylesheet" href="style.css?v=1">
<link rel="stylesheet" href="external.css?v=2">
```
I have a practice that when update any file change its version and upload so suppose changes are in style.css then change its version so browser take new file but still gets external.css from cache which is fine since i have stored this files in storage on client side. Now I am trying to automise versioning using gulp. So how to manage different versions for different files ?

**Comment by SkeLLLa** [comment]
@pinal-r this module can use only one version that's is set for the whole project. If you need versions per each file maybe it's better to use a different module that calculates hashes of each file and adds them as url param or in filename.
